### ISSUE TITLE
[feature request] mecab-jumandic support

### ISSUE THREAD

**Issue by tamuhey** [polm/unidic-lite#1]
Hi,

Are you planning to support mecab-jumandic?
Though it isn't very popular, [NICT BERT](https://alaginrc.nict.go.jp/nict-bert/index.html) uses the dictionary.

**Comment by polm** [comment]
I hadn't been planning on it, but sure, why not. It looks like it's about the same size as IPADic.

**Comment by tamuhey** [comment]
I want to use NICT BERT with huggingface/transformers, which uses fugashi as a tokenizer.
Is there  anything I can help with?

**Comment by polm** [comment]
I released version 0 of jumandic for testing, could you confirm it works? 

https://pypi.org/project/jumandic/0.0.0/

Beyond that I think Transformers will need a PR like [this one](https://github.com/huggingface/transformers/pull/6515), maybe you can do that? It might be better to change it to take an arbitrary tokenizer...

**Comment by tamuhey** [comment]
Wow incredibly fast! I've confirmed it works!

> Beyond that I think Transformers will need a PR like this one, maybe you can do that?

Yes, of course.

> It might be better to change it to take an arbitrary tokenizer...

I agree. At least I'd be nice if the Mecab arg is able to be configured more finely.

**Comment by polm** [comment]
Great, I'll release it as 1.0 soon then. 

If you make a PR to Transformers please @ me, or if you need help let me know.

**Comment by polm** [comment]
Released 1.0. If there are any issues please open them on the jumandic-py repo.
