### ISSUE TITLE
UniDic 2.2.0 support?

### ISSUE THREAD

**Issue by joshdavham** [polm/unidic-lite#2]
I'm implementing a paper right now using this library but am getting inconsistent results. I believe that the inconsistency stems from the fact that the authors were using UniDic 2.2.0 while this library is using UniDic 2.1.2.

Is there a possibility of UniDic 2.2.0 support in the future? If not, how would you suggest getting UniDic 2.2.0 to work with Fugashi, if possible?

Thanks!

**Comment by polm** [comment]
The packaged UniDics are distributed for convenience, mainly (by numbers) for people who are using them without even realizing it. But user-supplied dictionaries still work just like MeCab, so you can build UniDic according to the instructions, and then you just pass the `-d` flag like so:

```
import fugashi

tagger = fugashi.GenericTagger("-d path/to/unidic")
```

You probably don't have to use the GenericTagger, but it should work with any dictionary.

Given this and the lack of demand, I'm not thinking of packaging older versions of UniDic.
